create table if not exists countries
(
    id        bigint generated by default as identity primary key,
    name      varchar(255),
    continent varchar(255)
);

create table if not exists guests
(
    id         bigint generated by default as identity primary key,
    name       varchar(255),
    surname    varchar(255),
    country_id bigint,
    foreign key (country_id) references countries (id) on delete SET NULL
);

create table if not exists hosts
(
    id         bigint generated by default as identity primary key,
    name       varchar(255),
    surname    varchar(255),
    country_id bigint,
    foreign key (country_id) references countries (id) on delete SET NULL
);

create table if not exists hosts_guests
(
    host_id  bigint,
    guest_id bigint,
    primary key (host_id, guest_id),
    foreign key (host_id) references hosts (id) on delete SET NULL,
    foreign key (guest_id) references guests (id) on delete SET NULL
);

create table if not exists accommodations
(
    id       bigint generated by default as identity primary key,
    name     varchar(255),
    category varchar(255),
    host_id  bigint,
    numRooms int,
    isRented boolean,
    foreign key (host_id) references hosts (id) on delete SET NULL
);

create table if not exists users
(
    username                   varchar(255)
        primary key,
    password                   varchar(255),
    name                       varchar(255),
    surname                    varchar(255),
    is_account_non_expired     boolean default true,
    is_account_non_locked      boolean default true,
    is_credentials_non_expired boolean default true,
    is_enabled                 boolean default true,
    role                       varchar(50)

);

create table if not exists reservations
(
    id            bigint generated by default as identity
        primary key,
    date_created  timestamp,
    user_username varchar(255) references users,
    status        varchar(50)
);

create table if not exists reservations_accommodations
(
    reservation_id   bigint not null,
    accommodation_id bigint not null,
    primary key (reservation_id, accommodation_id),
    foreign key (reservation_id) references reservations (id) on delete SET NULL,
    foreign key (accommodation_id) references accommodations (id) on delete SET NULL
);

ALTER TABLE accommodations
    ALTER COLUMN host_id DROP NOT NULL;

ALTER TABLE guests
    ALTER COLUMN country_id DROP NOT NULL;

ALTER TABLE hosts
    ALTER COLUMN country_id DROP NOT NULL;

ALTER TABLE hosts_guests
    ALTER COLUMN host_id DROP NOT NULL;

ALTER TABLE hosts_guests
    ALTER COLUMN guest_id DROP NOT NULL;

ALTER TABLE reservations_accommodations
    ALTER COLUMN reservation_id DROP NOT NULL;

ALTER TABLE reservations_accommodations
    ALTER COLUMN accommodation_id DROP NOT NULL;

